src/Entity/BikesStock.php
<?php

namespace App\Entity;

use App\Repository\BikesStockRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BikesStockRepository::class)
 */
class BikesStock
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $deposit_date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\OneToOne(targetEntity=Operation::class, mappedBy="bikesStock", cascade={"persist", "remove"})
     */
    private $operation;

   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDepositDate(): ?\DateTimeInterface
    {
        return $this->deposit_date;
    }

    public function setDepositDate(?\DateTimeInterface $deposit_date): self
    {
        $this->deposit_date = $deposit_date;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getOperation(): ?Operation
    {
        return $this->operation;
    }

    public function setOperation(?Operation $operation): self
    {
        // unset the owning side of the relation if necessary
        if ($operation === null && $this->operation !== null) {
            $this->operation->setBikesStock(null);
        }

        // set the owning side of the relation if necessary
        if ($operation !== null && $operation->getBikesStock() !== $this) {
            $operation->setBikesStock($this);
        }

        $this->operation = $operation;

        return $this;
    }

   
}

src/Entity/NewStock.php
<?php

namespace App\Entity;

use App\Repository\NewStockRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NewStockRepository::class)
 */
class NewStock
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $label;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $brand;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $unit_price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Requirement::class, inversedBy="newStocks")
     */
    private $requirement;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $requirement_quantity;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLabel(): ?string
    {
        return $this->label;
    }

    public function setLabel(?string $label): self
    {
        $this->label = $label;

        return $this;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(?string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getUnitPrice(): ?float
    {
        return $this->unit_price;
    }

    public function setUnitPrice(?float $unit_price): self
    {
        $this->unit_price = $unit_price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getRequirement(): ?Requirement
    {
        return $this->requirement;
    }

    public function setRequirement(?Requirement $requirement): self
    {
        $this->requirement = $requirement;

        return $this;
    }

    public function getRequirementQuantity(): ?int
    {
        return $this->requirement_quantity;
    }

    public function setRequirementQuantity(?int $requirement_quantity): self
    {
        $this->requirement_quantity = $requirement_quantity;

        return $this;
    }
}

src/Entity/Repair.php
<?php

namespace App\Entity;

use App\Repository\RepairRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=RepairRepository::class)
 */
class Repair
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $takingCareDate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $doneDate;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $laborCost;

   

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $validation;

    /**
     * @ORM\OneToOne(targetEntity=Operation::class, mappedBy="repair", cascade={"persist", "remove"})
     */
    private $operation;

    /**
     * @ORM\OneToMany(targetEntity=BikeArticle::class, mappedBy="repair")
     */
    private $bikeArticles;

    /**
     * @ORM\OneToOne(targetEntity=Requirement::class, inversedBy="repair", cascade={"persist", "remove"})
     */
    private $requirement;

   

    

    public function __construct()
    {
        $this->bikeArticles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTakingCareDate(): ?\DateTimeInterface
    {
        return $this->takingCareDate;
    }

    public function setTakingCareDate(\DateTimeInterface $takingCareDate): self
    {
        $this->takingCareDate = $takingCareDate;

        return $this;
    }

    public function getDoneDate(): ?\DateTimeInterface
    {
        return $this->doneDate;
    }

    public function setDoneDate(?\DateTimeInterface $doneDate): self
    {
        $this->doneDate = $doneDate;

        return $this;
    }

    public function getLaborCost(): ?float
    {
        return $this->laborCost;
    }

    public function setLaborCost(?float $laborCost): self
    {
        $this->laborCost = $laborCost;

        return $this;
    }

   

  
    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): self
    {
        $this->comments = $comments;

        return $this;
    }

    public function getValidation(): ?bool
    {
        return $this->validation;
    }

    public function setValidation(?bool $validation): self
    {
        $this->validation = $validation;

        return $this;
    }

    public function getOperation(): ?Operation
    {
        return $this->operation;
    }

    public function setOperation(?Operation $operation): self
    {
        // unset the owning side of the relation if necessary
        if ($operation === null && $this->operation !== null) {
            $this->operation->setRepair(null);
        }

        // set the owning side of the relation if necessary
        if ($operation !== null && $operation->getRepair() !== $this) {
            $operation->setRepair($this);
        }

        $this->operation = $operation;

        return $this;
    }

    /**
     * @return Collection|BikeArticle[]
     */
    public function getBikeArticles(): Collection
    {
        return $this->bikeArticles;
    }

    public function addBikeArticle(BikeArticle $bikeArticle): self
    {
        if (!$this->bikeArticles->contains($bikeArticle)) {
            $this->bikeArticles[] = $bikeArticle;
            $bikeArticle->setRepair($this);
        }

        return $this;
    }

    public function removeBikeArticle(BikeArticle $bikeArticle): self
    {
        if ($this->bikeArticles->removeElement($bikeArticle)) {
            // set the owning side to null (unless already changed)
            if ($bikeArticle->getRepair() === $this) {
                $bikeArticle->setRepair(null);
            }
        }

        return $this;
    }

    public function getRequirement(): ?Requirement
    {
        return $this->requirement;
    }

    public function setRequirement(?Requirement $requirement): self
    {
        $this->requirement = $requirement;

        return $this;
    }

   

   
   
}

src/Form/RepairType.php
<?php

namespace App\Form;

use App\Entity\Repair;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RepairType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('takingCareDate',DateTimeType::class,[
                'label'=>'Taking Care Date',
                'data'=>new \DateTime('now'),
                'widget'=>'single_text'
            ])
            //->add('doneDate')
            ->add('laborCost',NumberType::class,[
                'label'=>'Labor Cost in Euro'
            ])
           
            ->add('comments',TextareaType::class,[
                'label'=>'Comments',
                'required'=>false
            ])
            //->add('validation')
            //->add('operation')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Repair::class,
        ]);
    }
}

src/Controller/RepairController.php
<?php

namespace App\Controller;

use App\Entity\BikeArticle;
use App\Entity\Operation;
use App\Entity\Repair;
use App\Entity\Requirement;
use App\Form\BikeArticleType;
use App\Form\RepairType;
use App\Form\RepairValidationType;
use App\Form\RequirementType;
use App\Repository\RepairRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/repair")
 */
class RepairController extends AbstractController
{
    /**
     * @Route("/", name="repair_index", methods={"GET"})
     */
    public function index(Request $request,RepairRepository $repairRepository): Response
    {
        $limit = 5;
        $page = (int)$request->query->get("page",1);
        $repairs = $repairRepository->getPaginatedRepair($page,$limit);
        $total=$repairRepository->getTotalRepair();
        return $this->render('repair/index.html.twig', [
            'repairs' => $repairs,
            'limit'=>$limit,
            'page'=>$page,
            'total'=>$total,
        ]);
    }

    /**
     * @Route("/currentRepairList", name="current_repair_list", methods={"GET"})
     */
    public function currentRepairList(Request $request,RepairRepository $repairRepository)
    {
        $limit = 5;
        $page=(int)$request->query->get("page",1);
        $totalCurrentRepair=$repairRepository->getTotalCurrentRepair();
        return $this->render('repair/currentRepairList.html.twig',[
            'currentRepairList'=>$repairRepository->findBy(["validation"=>null],["takingCareDate"=>"DESC"]),
            'limit'=>$limit,
            'page'=>$page,
            'total'=>$totalCurrentRepair,
        ]);
    }

    /**
     * @Route("/new", name="repair_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $repair = new Repair();
        $formRepair = $this->createForm(RepairType::class, $repair);
        $formRepair->handleRequest($request);

        if ($formRepair->isSubmitted() && $formRepair->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($repair);
            $entityManager->flush();

            return $this->redirectToRoute('repair_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('repair/new.html.twig', [
            'repair' => $repair,
            'formRepair' => $formRepair,
        ]);
    }

    /**
     * @Route("/{id}", name="repair_show", methods={"GET"})
     */
    public function show(Repair $repair): Response
    {
        return $this->render('repair/show.html.twig', [
            'repair' => $repair,
        ]);
    }

    /**
     * @Route("/{id}/estimate", name="repair_estimate", methods={"GET"})
     */
    public function estimate(Repair $repair):Response
    {
        return $this->render('repair/estimate.html.twig',[
            'repair'=>$repair,
        ]);
    }

    /**
     *@Route("/{id}/check_bike_part", name="check_bike_part", methods={"GET","POST"})
     */
    public function checkBikePart(Request $request, Repair $repair)
    {
        $bikeArticle = new BikeArticle();
        $formBikeArticle = $this->createForm(BikeArticleType::class,$bikeArticle);
        $formBikeArticle->handleRequest($request);

        if($formBikeArticle->isSubmitted() && $formBikeArticle->isValid())
        {
            $entityManager= $this->getDoctrine()->getManager();
            $repair->addBikeArticle($bikeArticle);
            $entityManager->persist($bikeArticle);
            $entityManager->flush();

            return $this->redirectToRoute('bike_article_show',['id'=>$bikeArticle->getId()]);
        }
        return $this->render('bike_article/new.html.twig',[
            'bikeArticle'=>$bikeArticle,
            'formBikeArticle'=>$formBikeArticle->createView(),
        ]);
    }

    /**
     * @Route("/{id}/addRequirement", name="add_requirement", methods={"GET","POST"})
     */
    public function addRequirement(Request $request, Repair $repair)
    {
        $requirement = new Requirement();
        $formRequirement = $this->createForm(RequirementType::class,$requirement);
        $formRequirement->handleRequest($request);

        if($formRequirement->isSubmitted() && $formRequirement->isValid())
        {
            $entityManager= $this->getDoctrine()->getManager();
           $repair->setRequirement($requirement);
           $entityManager->persist($requirement);
           $entityManager->persist($repair);
           $entityManager->flush();

           return $this->redirectToRoute('requirement_show',['id'=>$repair->getId()]);

        }
        return $this->render('requirement/new.html.twig',[
            'requirement'=>$requirement,
            'formRequirement'=>$formRequirement->createView(),
        ]);
    }

    /**
     * @Route("/{id}/repairValidation", name="repair_validation",methods={"GET","POST"})
     */
    public function repairValidation(Request $request, Repair $repair)
    {
        $formRepairValidation = $this->createForm(RepairValidationType::class,$repair);
        $formRepairValidation->handleRequest($request);

        if($formRepairValidation->isSubmitted() && $formRepairValidation->isValid())
        {
            $entityManager= $this->getDoctrine()->getManager();
            $entityManager->persist($repair);
            $entityManager->flush();

            return $this->redirectToRoute('repair_show',['id'=>$repair->getId()]);
        }
        return $this->render('repair/validation.html.twig',[
            'repairValidation'=>$repair,
            'formRepairValidation'=>$formRepairValidation->createView(),
        ]);
    }

    /**
     * @Route("/{id}/edit", name="repair_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Repair $repair): Response
    {
        $formRepair = $this->createForm(RepairType::class, $repair);
        $formRepair->handleRequest($request);

        if ($formRepair->isSubmitted() && $formRepair->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('repair_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('repair/edit.html.twig', [
            'repair' => $repair,
            'formRepair' => $formRepair,
        ]);
    }

    /**
     * @Route("/{id}", name="repair_delete", methods={"POST"})
     */
    public function delete(Request $request, Repair $repair): Response
    {
        if ($this->isCsrfTokenValid('delete'.$repair->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($repair);
            $entityManager->flush();
        }

        return $this->redirectToRoute('repair_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/repair/_delete_form.html.twig
<form method="post" action="{{ path('repair_delete', {'id': repair.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ repair.id) }}">
    <button class="btn delete"><i class="bi bi-trash"></i></button>
</form>

templates/repair/_form.html.twig
{{ form_start(formRepair) }}
    {{ form_widget(formRepair) }}
    <button class="btn create">{{ button_label|default('Save') }}</button>
{{ form_end(formRepair) }}

templates/repair/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Repair{% endblock %}

{% block body %}
<div class="container-fluid list">
{% form_theme formRepair 'bootstrap_4_layout.html.twig' %}
    <h1>Edit Repair</h1>

    {{ include('repair/_form.html.twig', {'button_label': 'Update'}) }}
 {{ include('repair/_delete_form.html.twig') }}
    <a class="btn create" href="{{ path('repair_index') }}"><i class="bi bi-chevron-left"> Back to list</i></a>

   
    </div>
{% endblock %}

templates/repair/estimate.html.twig
{% extends "base.html.twig" %}
{% block title %}Estimate
{% endblock %}
{% block body %}
	<div class="container-fluid list">
		<h1>Estimate  Bike N°
			{{repair.operation.bike.serialNumber}}</h1>
		<table class="table">
			<tbody>
				<tr>
					<th>Source</th>
					<td>
						<div class="row">
							<div class="col-sm">
								<div>Origin :
									{{repair.operation.bike.source.origin}}</div>
							</div>
							<div class="col-sm">
								<div>Purpose :
									{{repair.operation.bike.source.purpose}}</div>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<th>Contact</th>
					<td>
						<div class="row">
							<div class="col-sm">
								<div>Phone Number :
									{{repair.operation.bike.source.telephone}}
								</div>
							</div>
							<div class="col-sm">
								<div>Email :
									{{repair.operation.bike.source.email}}
								</div>
							</div>
							<div class="col-sm">
								<div>Address :
									{{repair.operation.bike.source.Address}}
								</div>
							</div>
						</td>
					</td>
				</tr>
				<tr>
					<th>Bike</th>
					<td>
						<div class="row">
							<div class="col-sm">
								<div>Brand :
									{{repair.operation.bike.brand}}</div>
							</div>
							<div class="col-sm">
								<div>Category :
									{{repair.operation.bike.category}}
								</div>
							</div>
							<div class="col-sm">
								<div>Color :
									{{repair.operation.bike.color}}</div>
							</div>
							<div class="col-sm">
								<div>Size :
									{{repair.operation.bike.size}}</div>
							</div>
						</div>
					</td>
				</tr>
				<tr>
					<th>Operation</th>
					<td>
						<div class="row">
							<div class="col-sm">
								<div>Reception Date :
									{{repair.operation.receptionDate|date('Y-m-d H:i')}}</div>
							</div>

						</div>
					</td>
				</tr>
				<tr>
					<th>Operators</th>
					<td>
						{% for operator in repair.operation.operators %}
							<div>{{operator.role}}
							{{operator.firstName}}
							{{operator.lastName}}</div>
						
						{% endfor %}
					</td>
				</tr>
			</tbody>
		</table>
		<h2>Bike check on the
			{{repair.takingCareDate|date('Y-m-d H:i')}}</h2>
		<table class="table table-bordered">
			<tbody>
				{% if repair.bikeArticles != null %}
					{% for  bikeArticle in repair.bikeArticles %}
						<tr>
							<th>Main</th>
							<td>
								{% for article in bikeArticle.main %}
									<div>{{article}}</div>
								{% endfor %}
							</td>
						</tr>
						<tr>
							<th>Brake</th>
							<td>
								{% for article in bikeArticle.brake %}
									<div>{{article}}</div>
								{% endfor %}

							</td>
						</tr>
						<tr>
							<th>Wheel</th>
							<td>
								{% for article in bikeArticle.wheel %}
									<div>{{article}}</div>
								{% endfor %}
							</td>
						</tr>
						<tr>
							<th>Transmission</th>
							<td>
								{% for article in bikeArticle.transmission %}
									<div>{{article}}</div>
								{% endfor %}
							</td>
						</tr>
						<tr>
							<th>Crank</th>
							<td>
								{% for article in bikeArticle.crank %}
									<div>{{article}}</div>
								{% endfor %}
							</td>
						</tr>
						<tr>
							<th>Security</th>
							<td>
								{% for article in bikeArticle.security %}
									<div>{{article}}</div>
								{% endfor %}
							</td>
						</tr>
						<tr>
							<th>Comments</th>
							<td>
								<div>{{bikeArticle.comments}}</div>
							</td>
						</tr>
					{% endfor %}
				{% endif %}
			</tbody>
		</table>
		<h2>Requirements</h2>
		<table class="table table-bordered">
		
			{% if repair.requirement !=null %}
				<thead>
					<th>New article </th>
					<th>Brand</th>
					<th>Quantity</th>
					<th>Unit Price</th>
					<th>Total</th>
				</thead>
				<tbody>
					{% set totalNewStock = 0 %}
					{% for article in repair.requirement.newStocks %}
						<tr>
							<td>{{article.label}}</td>
							<td>{{article.brand}}</td>
							<td class="text-end">{{article.requirementQuantity}}</td>
							<td class="text-end">{{article.unitPrice}}
								€</td>
							<td class="text-end">{{article.unitPrice * article.requirementQuantity}}
								€</td>
							{% set totalNewStock = totalNewStock + article.unitPrice * article.requirementQuantity %}
						</tr>
					{% else %}
						<tr>
							<td colspan="5">No new stock requirement</td>
						</tr>
					{% endfor %}
				</tbody>
			
			<thead>
				<th>Second hand stock article Label</th>
				<th>Brand</th>
				<th>Quantity</th>
				<th>Unit Price</th>
				<th>Total</th>

			</thead>
			<tbody>
				{% set totalSecondHandStock = 0 %}
				{% for article in repair.requirement.secondHandStocks %}
					<tr>
						<td>{{article.label}}</td>
						<td>{{article.brand}}</td>
						<td class="text-end">{{article.requirementQuantity}}</td>
						<td class="text-end">{{article.unitPrice}}
							€</td>
						<td class="text-end">{{article.unitPrice * article.requirementQuantity}}
							€</td>
						{% set totalSecondHandStock = totalSecondHandStock + article.unitPrice * article.requirementQuantity %}
					</tr>
				{% else %}
					<tr>
						<td colspan="5" class="text-center">No second-hand stock requiremnent</td>
					</tr>
				{% endfor %}
			</tbody>
			<tr>
				<th>Labor Cost</th>
				<td colspan="4" class="text-center">{{repair.laborCost}}
					€</td>
			</tr>
			<tr>
				<th>Total requirement and labor cost</th>
				<td colspan="4" class="text-center">
					<strong>{{repair.laborCost + totalNewStock + totalSecondHandStock}}
					€</strong>
				</td>
			</tr>
			{% endif %}
		</table>
		<div class=" text-center estimate">This bike has been check by a professional</div>
		<div class="estimate">When you registered you have accepted that we collected your data and that it will not be used for commercial purposes and will be automatically destroyed after 2 years of inactivity or at your request
		</div>
		<div class="estimate">Signature :
		</div>
		<div class="row">
			<div class="col-sm">
				<a class="btn create" href="{{path('current_repair_list')}}">
					Repair Curent List</a>
			</div>
		</div>
	</div>
{% endblock %}

templates/repair/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Repair{% endblock %}

{% block body %}
<div class="container-fluid list">
{% form_theme formRepair 'bootstrap_4_layout.html.twig' %}
    <h1>Create new Repair</h1>

    {{ include('repair/_form.html.twig') }}

    <a class="btn create" href="{{ path('repair_index') }}"><i class="bi bi-chevron-left"> Back to list</i></a>
    </div>
{% endblock %}

templates/repair/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Repair{% endblock %}

{% block body %}
<div class="container-fluid list">
    <h1>Repair</h1>

    <table class="table table-bordered">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ repair.id }}</td>
            </tr>
            <tr>
                <th>Taking Care Date</th>
                <td>{{ repair.takingCareDate ? repair.takingCareDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Done Date</th>
                <td>{{ repair.doneDate ? repair.doneDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Labor Cost</th>
                <td>{{ repair.laborCost }} €</td>
            </tr>
           
            <tr>
                <th>Comments</th>
                <td>{{ repair.comments }}</td>
            </tr>
            <tr>
            <th>Repair Summary</th>
            <td>
            <a class="btn show" href="{{path('bike_article_show',{'id':repair.id})}}"><i class="bi bi-info-square"></i></a>
            </td>
            </tr>
            <tr>
                <th>Validation</th>
                <td>
                {% if repair.validation != true %}
                  
                    <div><a class="btn create" href="{{path('repair_validation',{'id':repair.id})}}">Validate</a></div>
               {% else %}
                    {% if repair.operation.billing != null %}
                        Repair has been billed the {{repair.operation.billing.billingDate|date('Y-m-d')}}
                    {% elseif repair.operation.bikesStock != null %}
                        Bike has been put in stock the {{repair.operation.bikesStock.depositDate|date('Y-m-d')}}
                    {% else %}
                      <div><a class="btn create" href="{{path('add_operator',{'id':repair.operation.id})}}"><i class="bi bi-plus-square"> Add operators</i></a></div>
                     <div><a class="btn create" href="{{path('add_billing',{'id':repair.operation.id})}}"><i class="bi bi-plus-square"> Billing</i></a></div>
                    <div><a class="btn create" href="{{path('add_bikes_stock',{'id':repair.operation.id})}}"><i class="bi bi-plus-square"> Add to bike stock</i></a></div>
                    {% endif %}
                   
               {% endif %}
                </td>
            </tr>
        </tbody>
    </table>
   
    <div class="row">
    <div class="col-sm">
    <a class="btn create" href="{{ path('repair_index') }}"><i class="bi bi-chevron-left"> Back to list</i></a>
    </div>
    {% if is_granted("ROLE_MANAGER") %}
    <div class="col-sm">
     {{ include('repair/_delete_form.html.twig') }}
    <a class="btn edit" href="{{ path('repair_edit', {'id': repair.id}) }}"><i class="bi bi-pencil"> Edit</i></a>
   </div>
    {% endif %}
    </div>
    </div>
{% endblock %}

templates/repair/validation.html.twig
{% extends "base.html.twig" %}
{% block title %}Repair Validation{% endblock %}
{% block body %}
{% form_theme formRepairValidation 'bootstrap_4_layout.html.twig' %}
<div class="container-fluid list">
<h1>Validation of the repair of the bike N°{{repairValidation.operation.bike.serialNumber}}</h1>
{{form_start(formRepairValidation)}}
{{form_widget(formRepairValidation)}}
<button class="btn create">{{button_label|default('Validate')}}</button>
{{form_end(formRepairValidation)}}
</div>
{% endblock %}