src/Entity/Transformation.php
<?php

namespace App\Entity;

use App\Repository\TransformationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TransformationRepository::class)
 */
class Transformation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $article_label;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $destination;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $quantity;

    /**
     * @ORM\ManyToOne(targetEntity=Recycling::class, inversedBy="transformations")
     */
    private $recycling;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getArticleLabel(): ?string
    {
        return $this->article_label;
    }

    public function setArticleLabel(?string $article_label): self
    {
        $this->article_label = $article_label;

        return $this;
    }

    public function getDestination(): ?string
    {
        return $this->destination;
    }

    public function setDestination(?string $destination): self
    {
        $this->destination = $destination;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getRecycling(): ?Recycling
    {
        return $this->recycling;
    }

    public function setRecycling(?Recycling $recycling): self
    {
        $this->recycling = $recycling;

        return $this;
    }
}

src/Form/TransformationType.php
<?php

namespace App\Form;

use App\Entity\Transformation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TransformationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('article_label',TextType::class,[
                'label'=>'Article label'
            ])
            ->add('destination',TextType::class,[
                'label'=>'Destination'
            ])
            ->add('quantity',NumberType::class,[
                'label'=>'Quantity'
            ])
            //->add('recycling')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Transformation::class,
        ]);
    }
}

src/Controller/TransformationController.php
<?php

namespace App\Controller;

use App\Entity\Transformation;
use App\Form\TransformationType;
use App\Repository\TransformationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/transformation")
 */
class TransformationController extends AbstractController
{
    /**
     * @Route("/", name="transformation_index", methods={"GET"})
     */
    public function index(TransformationRepository $transformationRepository): Response
    {
        return $this->render('transformation/index.html.twig', [
            'transformations' => $transformationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="transformation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $transformation = new Transformation();
        $formTransformation = $this->createForm(TransformationType::class, $transformation);
        $formTransformation->handleRequest($request);

        if ($formTransformation->isSubmitted() && $formTransformation->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($transformation);
            $entityManager->flush();

            return $this->redirectToRoute('transformation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('transformation/new.html.twig', [
            'transformation' => $transformation,
            'formTransformation' => $formTransformation,
        ]);
    }

    /**
     * @Route("/{id}", name="transformation_show", methods={"GET"})
     */
    public function show(Transformation $transformation): Response
    {
        return $this->render('transformation/show.html.twig', [
            'transformation' => $transformation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="transformation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Transformation $transformation): Response
    {
        $formTransformation = $this->createForm(TransformationType::class, $transformation);
        $formTransformation->handleRequest($request);

        if ($formTransformation->isSubmitted() && $formTransformation->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('transformation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('transformation/edit.html.twig', [
            'transformation' => $transformation,
            'formTransformation' => $formTransformation,
        ]);
    }

    /**
     * @Route("/{id}", name="transformation_delete", methods={"POST"})
     */
    public function delete(Request $request, Transformation $transformation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$transformation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($transformation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('transformation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/transformation/_delete_form.html.twig
<form method="post" action="{{ path('transformation_delete', {'id': transformation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ transformation.id) }}">
    <button class="btn delete"><i class="bi bi-trash"></i></button>
</form>

templates/transformation/_form.html.twig
{{ form_start(formTransformation) }}
    {{ form_widget(formTransformation) }}
    <button class="btn create">{{ button_label|default('Save') }}</button>
{{ form_end(formTransformation) }}

templates/transformation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Transformation{% endblock %}

{% block body %}
<div class="container-fluid fluid">
{% form_theme formTransformation 'bootstrap_4_layout.html.twig' %}
    <h1>Edit Transformation</h1>

    {{ include('transformation/_form.html.twig', {'button_label': 'Update'}) }}
 {{ include('transformation/_delete_form.html.twig') }}
    <a class="btn create" href="{{ path('transformation_index') }}"><i class="bi bi-chevron-left"> Back to list</i></a>

   
    </div>
{% endblock %}

templates/transformation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Transformations{% endblock %}

{% block body %}
<div class="container-fluid list">
    <h1>Transformations List</h1>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Id</th>
                <th>Article Label</th>
                <th>Destination</th>
                <th>Quantity</th>
                <th>Show</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
        {% for transformation in transformations %}
            <tr>
                <td>{{ transformation.id }}</td>
                <td>{{ transformation.articleLabel }}</td>
                <td>{{ transformation.destination }}</td>
                <td>{{ transformation.quantity }}</td>
                <td>
                    <a class="btn show" href="{{ path('transformation_show', {'id': transformation.id}) }}"><i class="bi bi-info-square"></i></a>
                    </td>
                    <td>
                    {% if is_granted("ROLE_MANAGER") %}
                          <div>
                    <a class="btn edit" href="{{ path('transformation_edit', {'id': transformation.id}) }}"><i class="bi bi-pencil"></i></a>
                </div>
                {{ include('transformation/_delete_form.html.twig') }}
                    {% else %}
                        <span col="2">Unauthorized access</span>
                    {% endif %}
                  
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">No records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

   
    </div>
{% endblock %}

templates/transformation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Transformation{% endblock %}

{% block body %}
<div class="container-fluid list">
{% form_theme formTransformation 'bootstrap_4_layout.html.twig' %}
    <h1>Create new Transformation</h1>

    {{ include('transformation/_form.html.twig') }}

    <a class="btn create" href="{{ path('transformation_index') }}"><i class="bi bi-chevron-left"> Back to list</i></a>
</div>
{% endblock %}

templates/transformation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Transformation{% endblock %}

{% block body %}
<div class="container-fluid list">
    <h1>Transformation</h1>

    <table class="table table-bordered">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ transformation.id }}</td>
            </tr>
            <tr>
                <th>Article Label</th>
                <td>{{ transformation.articleLabel }}</td>
            </tr>
            <tr>
                <th>Destination</th>
                <td>{{ transformation.destination }}</td>
            </tr>
            <tr>
                <th>Quantity</th>
                <td>{{ transformation.quantity }}</td>
            </tr>
        </tbody>
    </table>
    <div class="row">
    <div class="col-sm">
    <a class="btn create" href="{{ path('transformation_index') }}"><i class="bi bi-chevron-left"> Back to list</i></a>
</div>
{% if is_granted("ROLE_MANAGER") %}
<div class="col-sm">
  {{ include('transformation/_delete_form.html.twig') }}
    <a class="btn edit" href="{{ path('transformation_edit', {'id': transformation.id}) }}"><i class="bi bi-pencil"> Edit</i></a>
</div>
{% endif %}
   </div>
   </div>
{% endblock %}